services:
  app:
    container_name: flownau
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./prisma:/app/prisma
      - ./.env:/app/.env
      - /app/node_modules
      - ./.next:/app/.next
    # ports:
    #   - '3000:3000'
    environment:
      - NODE_ENV=development
      # Internal network address
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_HOST=redis
    # depends_on:
    #   - postgres
    #   - redis
    command: npm run dev
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: flownau-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # Map to 5433 on host to avoid conflict with shared_postgres
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: flownau-redis
    restart: always
    ports:
      # Map to 6380 on host to avoid conflict with shared_redis
      - '6380:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
