version: '3.8'

services:
  # Disable local database and redis - we use the ones from 'infrastructure'
  postgres:
    profiles: ["donotstart"]
  redis:
    profiles: ["donotstart"]

  # Main Web App
  app:
    networks:
      - shared-mesh
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@shared_postgres:5432/${POSTGRES_DB}?schema=public
      - REDIS_HOST=shared_redis
    depends_on: [] # Infrastructure should be up already

  # Background Worker
  worker:
    networks:
      - shared-mesh
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@shared_postgres:5432/${POSTGRES_DB}?schema=public
      - REDIS_HOST=shared_redis
    depends_on: []

networks:
  shared-mesh:
    external: true
